export const ADD_TOPPINGS = 'ADD_TOPPINGS';
export const CHOOSE_TOPPINGS = 'CHOOSE_TOPPINGS';
export const REMOVE_TOPPINGS = 'REMOVE_TOPPINGS';
export const CHANGE_TOPPING_ITEM_STATUS = 'CHANGE_TOPPING_ITEM_STATUS';
